export type Project = {
    name: string;
    description: string;
    technologies: Tech[];
    links: ProjectLink[];
};

type Tech = {
    name: string;
    badgeColor: string;
}

const flutter: Tech = {name: 'flutter', badgeColor: '#0468d7'};
const nextjs: Tech = {name: 'nextjs', badgeColor: '#0a0a0a'};
const nodejs: Tech = {name: 'nodejs', badgeColor: '#84BA64'};
const cloudfunction: Tech = {name: 'cloud function', badgeColor: '#fb923c'};
const openai: Tech = {name: 'openai', badgeColor: '#10a37f'};
const reactnative: Tech = {name: 'reactnative', badgeColor: '#61dafb'};
const tailwind: Tech = {name: 'tailwind', badgeColor: '#38BDF8'};
const firebase: Tech = {name: 'firebase', badgeColor: '#fbbf24'};
const supabase: Tech = {name: 'supabase', badgeColor: '#84BA64'};

type ProjectLink = {
    name: 'github' | 'web' | 'appstore' | 'playstore';
    url: string;
};

export const projects: Project[] = [
    {
        name: 'Flip3',
        description: 'A secure, permissionless and incentivised Peer-to-Peer crypto to fiat platform.',
        technologies: [flutter, nodejs],
        links: [
            {
                name: 'web',
                url: 'https://flip3.xyz',
            },
        ],
    },
    {
        name: 'Feastpass',
        description: 'FeastPass is the most flexible, community engagement and rewards platform helping local vendors boost in-store sales by engaging customers through experiences, content, and discounts.',
        technologies: [nextjs, reactnative],
        links: [
            {
                name: 'web',
                url: 'https://feastpass.com',
            },
        ],
    },
    {
        name: 'Pokedex',
        description: 'A Pokedex App: Demonstrating Layered Architecture, Separation of Concerns, and Thorough Testing.',
        technologies: [flutter],
        links: [
            {
                name: 'github',
                url: 'https://github.com/iamstanlee/pokedex',
            },
        ],
    }, {
        name: 'Linkfy Text',
        description:
            'A lightweight Flutter package that can identify and convert URLs, emails, and hashtags in a text string into clickable links, similar to the way Twitter handles them.',
        technologies: [flutter],
        links: [
            {
                name: 'github',
                url: 'https://github.com/Iamstanlee/linkfy_text',
            },
        ],
    }, {
        name: 'xGPT',
        description: 'Personalized and contextual AI chat bot',
        technologies: [nextjs, tailwind, openai],
        links: [
            {
                name: 'web',
                url: 'https://x-gpt.stanlee.dev',
            },
            {
                name: 'github',
                url: 'https://github.com/Iamstanlee/x_gpt',
            },
        ],
    }, {
        name: 'MuqeeAI',
        description: 'Content creation on autopilot 🗓, Get daily rich and exceptional content generated by AI, tailored to your brand\'s unique voice and style.',
        technologies: [nextjs, tailwind, supabase],
        links: [
            {
                name: 'web',
                url: 'https://muqee.ai',
            },
        ],
    },
    {
        name: 'Kivifood',
        description: 'An app that enables users to order food for delivery or pickup from local restaurants from the convenience of their own homes.',
        technologies: [flutter, firebase, cloudfunction],
        links: [
            {
                name: 'playstore',
                url: 'https://play.google.com/store/apps/details?id=com.kivifood.app',
            },
            {
                name: 'appstore',
                url: 'https://apps.apple.com/us/app/kivi-food/id1588631598',
            },
        ],
    },
    {
        name: 'Kivifood (vendor app)',
        description: 'An app that allows businesses to easily manage food orders, accept payments, and keep track of their inventory.',
        technologies: [flutter, firebase, cloudfunction],
        links: [
            {
                name: 'playstore',
                url: 'https://play.google.com/store/apps/details?id=com.kivifood.vendor',
            },
            {
                name: 'appstore',
                url: 'https://apps.apple.com/us/app/kivifood-vendor/id1588656247',
            },
        ],
    },
];
